# Simple workflow for deploying static content to GitHub Pages
name: CI/CD Pull Requests Pipeline CSE 270

on:
  pull_request:
    branches: ["master", "staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v4.1.2
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'
        cache: "npm"
    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install
    
    - name: Lint with Eslint
      run: |
        yarn run lint

    - name: Run tests
      run: |
        yarn run test

    
  analyze:
    needs: build
    uses: ./.github/workflows/code-analysis.yml
    with:
      language: 'javascript'

  deploy:
    needs: analyze
    environment:
      name: Production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      #- name: Install Vercel CLI
      #  run: npm install -g vercel

      #- name: Deploy to Vercel
      #  env:
      #    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #  run: |
      #    vercel --prod --confirm --token $VERCEL_TOKEN

