name: 'QA Pipeline'


on:
  push:
    branches: ['test']
  pull_request:
    branches: ['test']
    types: [synchronize, labeled, opened, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Test
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4.1.2
      - name: Setup Node 22
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.14.0
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Lint with Eslint
        run: |
          yarn run lint
      - name: Run Tests
        run: |
          yarn test:cov

  analyze:
    needs: build
    uses: ./.github/workflows/code-analysis.yml
    with:
      language: 'javascript'

  deploy:
    needs: analyze
    uses: ./.github/workflows/pr-merge.yml
    with:
      pr_number: "${{ github.event.pull_request.number }}"
      github_repo: "${{ github.repository }}"
